name: dwg-analyzer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit=1.28.0
  - pandas=2.0.0
  - numpy=1.24.0
  - plotly=5.15.0
  - matplotlib=3.7.0
  - scipy=1.11.0
  - scikit-learn=1.3.0
  - pip
  - pip:
    - ezdxf==1.4.2
    - shapely==2.0.0
    - reportlab==4.0.0
    - opencv-python-headless==4.8.0
    - google-generativeai==0.3.0
    - pydantic==2.0.0
    - networkx==3.0.0