services:
  - type: web
    name: enterprise-ilot-placement-system
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src"