[server]
maxUploadSize = 10000
maxMessageSize = 10000
headless = true
port = 5000
address = "0.0.0.0"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
base = "light"
