# Add this file to .streamlit/secrets.toml for Streamlit Cloud deployment
# Do not commit this file to version control

[database]
DATABASE_URL = "postgresql://de_de:PUPB8V0s2b3bvNZUblolz7d6UM9bcBzb@dpg-d1h53rffte5s739b1i40-a.oregon-postgres.render.com/dwg_analyzer_pro"
